const ACTIONS = {
  PATIENT_ADD: "PATIENT_ADD",
  PATIENT_REMOVE: "PATIENT_REMOVE",
  PATIENT_GET_ALL: "PATIENT_GET_ALL",
  PATIENT_REQUEST_GET_ALL: "PATIENT_REQUEST_GET_ALL"
};

export default ACTIONS;
