const ACTIONS = {
  PATIENT_ADD: "PATIENT_ADD",
  PATIENT_REQUEST_REMOVE: "PATIENT_REMOVE",
  PATIENT_GET_ALL: "PATIENT_GET_ALL",
  PATIENT_REQUEST_GET_ALL: "PATIENT_REQUEST_GET_ALL",
  PATIENT_REQUEST_ADD: "PATIENT_REQUEST_ADD",
  PATIENT_GET: "PATIENT_GET",
  PATIENT_LOAD: "PATIENT_LOAD",
  PATIENT_UPDATE: "PATIENT_UPDATE"
};

export default ACTIONS;
